### ISSUE TITLE
crash when all antivirus are disabled one by one in configuration

### ISSUE THREAD

**Issue by alevoski** [alevoski/decontamine_Linux#9]
**Crash**
A crash occurs when all antivirus have been disabled one by one when we return to main, even if we enable one again before.

**To Reproduce**
- go to the configurator (press "c")
- press "3" then disable all antivirus
- press "e" to exit the configurator

**Expected behavior**
A crash occurs with this message :
```
Traceback (most recent call last):
  File "/decontamine_linux.py", line 17, in <module>
    main()
  File "/decontamine_linux.py", line 13, in main
    decontamine.init()
  File "/CS/main.py", line 102, in init
    init()
  File "/CS/main.py", line 80, in init
    commontools.createTable(res, 'Name', 'Version')
  File "/CS/commontools.py", line 46, in createTable
    for item, value in theDict.items():
AttributeError: 'bool' object has no attribute 'items'
```

**Additional context**
All antivirus on the station were activated before I disabled them.

**Comment by alevoski** [comment]
Resolve with commit id 6152ddf
